### ISSUE TITLE
How to serialize webhook events?

### ISSUE THREAD

**Issue by criemen** [yanyongyu/githubkit#37]
Hi,

I want to serialize webhook events (`workflow_run` in particular).

I do

```python
    event_name = request.headers['X-GitHub-Event']
    event: WebhookEvent = parse(event_name, request.data)
    parse_obj_without_name(event.json())
```
to get the JSON representation, and then try to read that back in with `parse_obj`, and then I get validation errors from pydantic.

```
 webserver | [2023-06-30T18:32:53.750+0200] {app.py:1744} ERROR - Exception on /github_hook [POST]
 webserver | Traceback (most recent call last):
 webserver | File "/opt/homebrew/lib/python3.10/site-packages/flask/app.py", line 2529, in wsgi_app
 webserver | response = self.full_dispatch_request()
 webserver | File "/opt/homebrew/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
 webserver | rv = self.handle_user_exception(e)
 webserver | File "/opt/homebrew/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
 webserver | rv = self.dispatch_request()
 webserver | File "/opt/homebrew/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
 webserver | return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
 webserver | File "/Users/criemen/repos/codeql-halo/plugins/github_webhook_receiver.py", line 121, in github_hook
 webserver | parse_obj_without_name(event.json())
 webserver | File "/opt/homebrew/lib/python3.10/site-packages/githubkit/webhooks/parse.py", line 21, in parse_obj_without_name
 webserver | return parse_obj_as(WebhookEvent, payload)
 webserver | File "pydantic/tools.py", line 38, in pydantic.tools.parse_obj_as
 webserver | File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
 webserver | pydantic.error_wrappers.ValidationError: 62 validation errors for ParsingModel[Union[Annotated[Union[githubkit.webhooks.models.BranchProtectionRuleCreated, githubkit.webhooks.models.BranchProtectionRuleDeleted, githubkit.webhooks.models.BranchProtectionRuleEdited], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], Annotated[Union[githubkit.webhooks.models.CheckRunCompleted, githubkit.webhooks.models.CheckRunCreated, githubkit.webhooks.models.CheckRunRequestedAction, githubkit.webhooks.models.CheckRunRerequested], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], Annotated[Union[githubkit.webhooks.models.CheckSuiteCompleted, githubkit.webhooks.models.CheckSuiteRequested, githubkit.webhooks.models.CheckSuiteRerequested], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], Annotated[Union[githubkit.webhooks.models.CodeScanningAlertAppearedInBranch, githubkit.webhooks.models.CodeScanningAlertClosedByUser, githubkit.webhooks.models.CodeScanningAlertCreated, githubkit.webhooks.models.CodeScanningAlertFixed, githubkit.webhooks.models.CodeScanningAlertReopened, githubkit.webhooks.models.CodeScanningAlertReopenedByUser], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], CommitCommentCreated, CreateEvent, DeleteEvent, Annotated[Union[githubkit.webhooks.models.DependabotAlertCreated, githubkit.webhooks.models.DependabotAlertDismissed, githubkit.webhooks.models.DependabotAlertFixed, githubkit.webhooks.models.DependabotAlertReintroduced, githubkit.webhooks.models.DependabotAlertReopened], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], Annotated[Union[githubkit.webhooks.models.DeployKeyCreated, githubkit.webhooks.models.DeployKeyDeleted], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], DeploymentCreated, DeploymentProtectionRuleRequested, DeploymentStatusCreated, Annotated[Union[githubkit.webhooks.models.DiscussionAnswered, githubkit.webhooks.models.DiscussionCategoryChanged, githubkit.webhooks.models.DiscussionCreated, githubkit.webhooks.models.DiscussionDeleted, githubkit.webhooks.models.DiscussionEdited, githubkit.webhooks.models.DiscussionLabeled, githubkit.webhooks.models.DiscussionLocked, githubkit.webhooks.models.DiscussionPinned, githubkit.webhooks.models.DiscussionTransferred, githubkit.webhooks.models.DiscussionUnanswered, githubkit.webhooks.models.DiscussionUnlabeled, githubkit.webhooks.models.DiscussionUnlocked, githubkit.webhooks.models.DiscussionUnpinned], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], Annotated[Union[githubkit.webhooks.models.DiscussionCommentCreated, githubkit.webhooks.models.DiscussionCommentDeleted, githubkit.webhooks.models.DiscussionCommentEdited], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], ForkEvent, GithubAppAuthorizationRevoked, GollumEvent, Annotated[Union[githubkit.webhooks.models.InstallationCreated, githubkit.webhooks.models.InstallationDeleted, githubkit.webhooks.models.InstallationNewPermissionsAccepted, githubkit.webhooks.models.InstallationSuspend, githubkit.webhooks.models.InstallationUnsuspend], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], Annotated[Union[githubkit.webhooks.models.InstallationRepositoriesAdded, githubkit.webhooks.models.InstallationRepositoriesRemoved], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], InstallationTargetRenamed, Annotated[Union[githubkit.webhooks.models.IssueCommentCreated, githubkit.webhooks.models.IssueCommentDeleted, githubkit.webhooks.models.IssueCommentEdited], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], Annotated[Union[githubkit.webhooks.models.IssuesAssigned, githubkit.webhooks.models.IssuesClosed, githubkit.webhooks.models.IssuesDeleted, githubkit.webhooks.models.IssuesDemilestoned, githubkit.webhooks.models.IssuesEdited, githubkit.webhooks.models.IssuesLabeled, githubkit.webhooks.models.IssuesLocked, githubkit.webhooks.models.IssuesMilestoned, githubkit.webhooks.models.IssuesOpened, githubkit.webhooks.models.IssuesPinned, githubkit.webhooks.models.IssuesReopened, githubkit.webhooks.models.IssuesTransferred, githubkit.webhooks.models.IssuesUnassigned, githubkit.webhooks.models.IssuesUnlabeled, githubkit.webhooks.models.IssuesUnlocked, githubkit.webhooks.models.IssuesUnpinned], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], Annotated[Union[githubkit.webhooks.models.LabelCreated, githubkit.webhooks.models.LabelDeleted, githubkit.webhooks.models.LabelEdited], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], Annotated[Union[githubkit.webhooks.models.MarketplacePurchaseCancelled, githubkit.webhooks.models.MarketplacePurchaseChanged, githubkit.webhooks.models.MarketplacePurchasePendingChange, githubkit.webhooks.models.MarketplacePurchasePendingChangeCancelled, githubkit.webhooks.models.MarketplacePurchasePurchased], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], Annotated[Union[githubkit.webhooks.models.MemberAdded, githubkit.webhooks.models.MemberEdited, githubkit.webhooks.models.MemberRemoved], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], Annotated[Union[githubkit.webhooks.models.MembershipAdded, githubkit.webhooks.models.MembershipRemoved], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], MergeGroupChecksRequested, MetaDeleted, Annotated[Union[githubkit.webhooks.models.MilestoneClosed, githubkit.webhooks.models.MilestoneCreated, githubkit.webhooks.models.MilestoneDeleted, githubkit.webhooks.models.MilestoneEdited, githubkit.webhooks.models.MilestoneOpened], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], Annotated[Union[githubkit.webhooks.models.OrgBlockBlocked, githubkit.webhooks.models.OrgBlockUnblocked], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], Annotated[Union[githubkit.webhooks.models.OrganizationDeleted, githubkit.webhooks.models.OrganizationMemberAdded, githubkit.webhooks.models.OrganizationMemberInvited, githubkit.webhooks.models.OrganizationMemberRemoved, githubkit.webhooks.models.OrganizationRenamed], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], Annotated[Union[githubkit.webhooks.models.PackagePublished, githubkit.webhooks.models.PackageUpdated], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], PageBuildEvent, PingEvent, Annotated[Union[githubkit.webhooks.models.ProjectClosed, githubkit.webhooks.models.ProjectCreated, githubkit.webhooks.models.ProjectDeleted, githubkit.webhooks.models.ProjectEdited, githubkit.webhooks.models.ProjectReopened], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], Annotated[Union[githubkit.webhooks.models.ProjectCardConverted, githubkit.webhooks.models.ProjectCardCreated, githubkit.webhooks.models.ProjectCardDeleted, githubkit.webhooks.models.ProjectCardEdited, githubkit.webhooks.models.ProjectCardMoved], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], Annotated[Union[githubkit.webhooks.models.ProjectColumnCreated, githubkit.webhooks.models.ProjectColumnDeleted, githubkit.webhooks.models.ProjectColumnEdited, githubkit.webhooks.models.ProjectColumnMoved], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], Annotated[Union[githubkit.webhooks.models.ProjectsV2ItemArchived, githubkit.webhooks.models.ProjectsV2ItemConverted, githubkit.webhooks.models.ProjectsV2ItemCreated, githubkit.webhooks.models.ProjectsV2ItemDeleted, githubkit.webhooks.models.ProjectsV2ItemEdited, githubkit.webhooks.models.ProjectsV2ItemReordered, githubkit.webhooks.models.ProjectsV2ItemRestored], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], PublicEvent, Annotated[Union[githubkit.webhooks.models.PullRequestAssigned, githubkit.webhooks.models.PullRequestAutoMergeDisabled, githubkit.webhooks.models.PullRequestAutoMergeEnabled, githubkit.webhooks.models.PullRequestClosed, githubkit.webhooks.models.PullRequestConvertedToDraft, githubkit.webhooks.models.PullRequestDemilestoned, githubkit.webhooks.models.PullRequestDequeued, githubkit.webhooks.models.PullRequestEdited, githubkit.webhooks.models.PullRequestEnqueued, githubkit.webhooks.models.PullRequestLabeled, githubkit.webhooks.models.PullRequestLocked, githubkit.webhooks.models.PullRequestMilestoned, githubkit.webhooks.models.PullRequestOpened, githubkit.webhooks.models.PullRequestReadyForReview, githubkit.webhooks.models.PullRequestReopened, githubkit.webhooks.models.PullRequestReviewRequestRemovedOneof0, githubkit.webhooks.models.PullRequestReviewRequestRemovedOneof1, githubkit.webhooks.models.PullRequestReviewRequestedOneof0, githubkit.webhooks.models.PullRequestReviewRequestedOneof1, githubkit.webhooks.models.PullRequestSynchronize, githubkit.webhooks.models.PullRequestUnassigned, githubkit.webhooks.models.PullRequestUnlabeled, githubkit.webhooks.models.PullRequestUnlocked], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], Annotated[Union[githubkit.webhooks.models.PullRequestReviewDismissed, githubkit.webhooks.models.PullRequestReviewEdited, githubkit.webhooks.models.PullRequestReviewSubmitted], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], Annotated[Union[githubkit.webhooks.models.PullRequestReviewCommentCreated, githubkit.webhooks.models.PullRequestReviewCommentDeleted, githubkit.webhooks.models.PullRequestReviewCommentEdited], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], Annotated[Union[githubkit.webhooks.models.PullRequestReviewThreadResolved, githubkit.webhooks.models.PullRequestReviewThreadUnresolved], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], PushEvent, Annotated[Union[githubkit.webhooks.models.RegistryPackagePublished, githubkit.webhooks.models.RegistryPackageUpdated], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], Annotated[Union[githubkit.webhooks.models.ReleaseCreated, githubkit.webhooks.models.ReleaseDeleted, githubkit.webhooks.models.ReleaseEdited, githubkit.webhooks.models.ReleasePrereleased, githubkit.webhooks.models.ReleasePublished, githubkit.webhooks.models.ReleaseReleased, githubkit.webhooks.models.ReleaseUnpublished], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], Annotated[Union[githubkit.webhooks.models.RepositoryArchived, githubkit.webhooks.models.RepositoryCreated, githubkit.webhooks.models.RepositoryDeleted, githubkit.webhooks.models.RepositoryEdited, githubkit.webhooks.models.RepositoryPrivatized, githubkit.webhooks.models.RepositoryPublicized, githubkit.webhooks.models.RepositoryRenamed, githubkit.webhooks.models.RepositoryTransferred, githubkit.webhooks.models.RepositoryUnarchived], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], RepositoryDispatchEvent, RepositoryImportEvent, Annotated[Union[githubkit.webhooks.models.RepositoryVulnerabilityAlertCreate, githubkit.webhooks.models.RepositoryVulnerabilityAlertDismiss, githubkit.webhooks.models.RepositoryVulnerabilityAlertReopen, githubkit.webhooks.models.RepositoryVulnerabilityAlertResolve], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], Annotated[Union[githubkit.webhooks.models.SecretScanningAlertCreated, githubkit.webhooks.models.SecretScanningAlertReopened, githubkit.webhooks.models.SecretScanningAlertResolved, githubkit.webhooks.models.SecretScanningAlertRevoked], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], SecretScanningAlertLocationCreated, Annotated[Union[githubkit.webhooks.models.SecurityAdvisoryPerformed, githubkit.webhooks.models.SecurityAdvisoryPublished, githubkit.webhooks.models.SecurityAdvisoryUpdated, githubkit.webhooks.models.SecurityAdvisoryWithdrawn], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], Annotated[Union[githubkit.webhooks.models.SponsorshipCancelled, githubkit.webhooks.models.SponsorshipCreated, githubkit.webhooks.models.SponsorshipEdited, githubkit.webhooks.models.SponsorshipPendingCancellation, githubkit.webhooks.models.SponsorshipPendingTierChange, githubkit.webhooks.models.SponsorshipTierChanged], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], Annotated[Union[githubkit.webhooks.models.StarCreated, githubkit.webhooks.models.StarDeleted], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], StatusEvent, Annotated[Union[githubkit.webhooks.models.TeamAddedToRepository, githubkit.webhooks.models.TeamCreated, githubkit.webhooks.models.TeamDeleted, githubkit.webhooks.models.TeamEdited, githubkit.webhooks.models.TeamRemovedFromRepository], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], TeamAddEvent, WatchStarted, WorkflowDispatchEvent, Annotated[Union[githubkit.webhooks.models.WorkflowJobCompleted, githubkit.webhooks.models.WorkflowJobInProgress, githubkit.webhooks.models.WorkflowJobQueued, githubkit.webhooks.models.WorkflowJobWaiting], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})], Annotated[Union[githubkit.webhooks.models.WorkflowRunCompleted, githubkit.webhooks.models.WorkflowRunInProgress, githubkit.webhooks.models.WorkflowRunRequested], FieldInfo(default=PydanticUndefined, discriminator='action', extra={})]]]
```

Is this use-case supported?

**Comment by yanyongyu** [comment]
`parse_obj` function requires the dict of event content. you can use this function like this:

```python
parse_obj_without_name(event.dict())
```

 if you want to parse the json string of event, you need:

```python
parse_without_name(event.json())
```

**Comment by criemen** [comment]
Hey,

thanks for your help!
I still hit issues, but using `event.json(exclude_unset=True)` finally worked - maybe the UNSET's from the JSON representation are not object-equal to the UNSET marker used in the `pydantic` schema checker, or something like that.
Anyways, my code works now, so I'm happy :)
